### PR TITLE
Revert the change of k8s resources because of Autopilot limits

### PR DESCRIPTION
**Pull request by harpener**
https://github.com/roihunter/gold-digger/pull/436#issuecomment-1569837329

@roihunter/pythonistas @david-hel @roiterorh 🙏 👍 🐍

### CODE REVIEW

**Comment by david-hel** [comment]
True! Also lowest memory limit is 500mb from what I read lately. Thought with multiple pods it can be lower but not.

**Comment by harpener** [comment]
@david-hel It's weird that the error says the limit is 250m whereas it is 100m too. 🙈

**Comment by david-hel** [comment]
@harpener yeah I was editing my comment :) lowest possible CPU is 0.25, lowest memory is 0.5G

**Comment by harpener** [comment]
Oh, so I should revert the changes in https://github.com/roihunter/gold-digger/pull/436 completely?

**Comment by david-hel** [comment]
I changed its okay. I just set CPU to 0.25 and memory to 0.5G. We will save at least 0.5 CPU because we have now 2x 0.5 sice golddigger has min 2 replicas by default.

**Pull request merged**
