### PR TITLE
Formatting, unifications, coala, automatic release

### PR DESCRIPTION
**Pull request by harpener**
I didn't add coala bear for docstrings, because it would require a lot more changes. :-)

@roihunter/pythonistas 🙏 👍 🐍

### CODE REVIEW

**Comment by harpener** [comment]
Jedna mala koalalala

**Comment by harpener** [comment]
Jedna mala koalalala

**Comment by DavidPrexta** [comment]
Coala found some errors that you can fix.<BR><BR>Project wide:<BR>|&nbsp; &nbsp; &nbsp; | [NORMAL] GitBear:<BR>|&nbsp; &nbsp; &nbsp; | BRANCH NAME WARNINGS:<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; Missing JIRA task number in branch name<BR>|&nbsp; &nbsp; &nbsp; | <BR>|&nbsp; &nbsp; &nbsp; | COMMITS WARNINGS:<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 4bd4c20 Remove staging from supported profiles<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; b98a49e Add automatic release<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 76860c6 Add coala<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; c53f322 Bump click for coala<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 23eeef8 Use global variables in deploy pipeline<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; f16d932 Make global variable upper-case and use f-strings<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 2f966a1 Define logging level in settings<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 32adc2b Unify logging format with other projects<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; b0a5bea Reformat code<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; 1e377d5 Optimize imports<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; Missing JIRA task number at the beginning of commit message<BR>|&nbsp; &nbsp; &nbsp; | <BR>|&nbsp; &nbsp; &nbsp; | PR DESCRIPTION WARNINGS:<BR>|&nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; Missing url to JIRA task at the beginning of the PR description<BR><BR>

**Comment by harpener** [comment]
Jedna mala koalalala

**Comment by harpener** [comment]
Btw, I noticed that deploy pipeline uses Jenkins Lady credential, so I used it also for Coala pipeline - maybe we should create a new credential here.

**Comment by harpener** [comment]
https://ci.roihunter.com/view/Gold%20Digger/job/Gold%20Digger%20Deploy%20master/configure
https://ci.roihunter.com/view/Gold%20Digger/job/Multifunctional%20pipeline%20-%20master/configure
https://ci.roihunter.com/view/Gold%20Digger/job/gold-digger-github-pr-coala/configure

pipeline

**Comment by harpener** [comment]
@roihunter/pythonistas Do we want to ignore debug logs?

**Comment by harpener** [comment]
@martinvy Changed logging level a very long time ago. :-) https://github.com/roihunter/gold-digger/pull/2

**Comment by miso-belica** [comment]
I am for ignoring DEBUG logs on master/staging. We had a discussion about this in BE team a few days ago. It's not good to log DEBUG logs on staging/production. These should be turned on only for local development.

**Pull request merged**
