### PR TITLE
RH-30891: Use custom graypy.

### PR DESCRIPTION
**Pull request by martinvy**
https://roihunter.atlassian.net/browse/RH-30891

@harpener please review & merge.

### CODE REVIEW

**Comment by martinvy** [comment]
I created `Pipfile.lock` from Docker container so it doesn't contain unwanted libs.
I am quite disappointed with the pipenv tool 😕

**Comment by Artimi** [comment]
@martinvy Have you tried poetry https://poetry.eustace.io/? Allegedly it is better. However, I didn't try it by myself so I don't know if it will be better.

**Comment by martinvy** [comment]
@Artimi thanks for the comment :) I already read Poetry's documentation some time ago and I liked it more than pipenv, but I didn't try it yet. I read good article [pipenv-promises-a-lot-delivers-very-little](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/) yesterday and I am considering to try poetry and maybe also [pip-tools](https://github.com/jazzband/pip-tools). But to be honest, I am not so sure about these tools and I am thinking about going back to just `pip` & `requirements.txt`.

**Comment by Artimi** [comment]
@martinvy We are using `pip` for a long time but recently it started to break repeatedly because of missing/very naive dependency resolver https://github.com/pypa/pip/issues/988. It basically installs the first version it finds and does not care that it will have a conflict with a dependency of some subpackage later. Good luck.

**Comment by harpener** [comment]
https://github.com/mhammond/pywin32/issues/1439

**Pull request merged**
